
version: '2.2'

services:

  differ_client:
    build:
      context: test_client
    image: cyberdojo/differ-client
    init: true
    container_name: test-differ-client
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'


  differ:
    build:
      context: .
      args:
        - SHA
    image: khacnhat/differ-dojo
    container_name: test-differ-server
    volumes:
      - ./test_server:/app/test:ro
    ports:
      - 4567:4567
    init: true
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'
